services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: kytucxa_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - kytucxa_postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - kytucxa_network

volumes:
  kytucxa_postgres_data:
    driver: local

networks:
  kytucxa_network:
    driver: bridge
