const REGISTRATION_STATUS = {
  DANG_KY: "DANG_KY",
  CHO_DUYET: "CHO_DUYET",
  DA_DUYET: "DA_DUYET",
  DA_TU_CHOI: "TU_CHOI",
};

const NGUYEN_VONG = {
  TU_GIA_HAN: "TU_GIA_HAN",
  KHONG_GIA_HAN: "KHONG_GIA_HAN",
};

module.exports = { REGISTRATION_STATUS, NGUYEN_VONG };
