const PAYMENT_TYPE = {
  TIEN_DIEN_NUOC: "TIEN_DIEN_NUOC",
  TIEN_PHONG: "TIEN_PHONG",
};

const PAYMENT_STATUS = {
  CHUA_THANH_TOAN: "CHUA_THANH_TOAN",
  DANG_CHO_THANH_TOAN: "DANG_CHO_THANH_TOAN",
  DA_THANH_TOAN: "DA_THANH_TOAN",
  HUY: "HUY",
  CHO_XAC_NHAN: "CHO_XAC_NHAN",
};

const PAYMENT_METHOD = {
  TIEN_MAT: "TIEN_MAT",
  CHUYEN_KHOAN: "CHUYEN_KHOAN",
};

module.exports = {
  PAYMENT_TYPE,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
};
