const PAYMENT_TYPE = {
  DIEN_NUOC: "DIEN_NUOC",
  PHONG: "PHONG",
};

const PAYMENT_STATUS = {
  CHUA_THANH_TOAN: "CHUA_THANH_TOAN",
  DANG_CHO_THANH_TOAN: "DANG_CHO_THANH_TOAN",
  DA_THANH_TOAN: "DA_THANH_TOAN",
  HUY: "HUY",
};

module.exports = {
  PAYMENT_TYPE,
  PAYMENT_STATUS,
};
