const YEU_CAU_CHUYEN_PHONG_STATUS = {
  CHO_DUYET: "CHO_DUYET",
  DA_DUYET: "DA_DUYET",
  TU_CHOI: "TU_CHOI",
  DANG_XU_LY: "DANG_XU_LY",
};

const YEU_CAU_CHUYEN_PHONG_STATUS_LABELS = {
  [YEU_CAU_CHUYEN_PHONG_STATUS.CHO_DUYET]: "Chờ duyệt",
  [YEU_CAU_CHUYEN_PHONG_STATUS.DA_DUYET]: "Đã duyệt",
  [YEU_CAU_CHUYEN_PHONG_STATUS.TU_CHOI]: "Từ chối",
  [YEU_CAU_CHUYEN_PHONG_STATUS.DANG_XU_LY]: "Đang xử lý",
};

module.exports = {
  YEU_CAU_CHUYEN_PHONG_STATUS,
  YEU_CAU_CHUYEN_PHONG_STATUS_LABELS,
};
